name: hf_vqa_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23
  - ipykernel
  # PyTorch + CUDA 12.1 via conda
  - pytorch=2.4.1
  - torchvision=0.19.1
  - torchaudio=2.4.1
  - pytorch-cuda=12.1
  - git  # needed for pip git+ installs
  - pip:
      - git+https://github.com/huggingface/transformers.git
      - git+https://github.com/huggingface/trl.git
      - datasets==3.6.0
      - bitsandbytes==0.46.0
      - peft==0.15.2
      - qwen-vl-utils==0.0.11
      - wandb==0.20.1
      - accelerate==1.8.1
      - Jinja2==3.1.6
      - vllm==0.10.1